services:
  onos:
    container_name: onos-controller
    networks:
      onos_test_network:
        ipv4_address: 172.0.0.2
    image: onosproject/onos:latest
    ports:
      - "6653:6653"
      - "6640:6640"
      - "8181:8181"
      - "8101:8101"
      - "5005:5005"
      - "9876:9876"
    volumes:
      - ./onos-config:/root/onos-config
      - ./onos-apps:/root/onos-apps
    environment:
      - JAVA_DEBUG_PORT=0.0.0.0:5005
      - ONOS_APPS=drivers,openflow,lldpprovider,gui2,fwd
    
  mininet:
    container_name: mininet
    networks:
      onos_test_network:
        ipv4_address: 172.0.0.3
    image: iwaseyusuke/mininet:latest
    tty: true
    stdin_open: true
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /lib/modules:/lib/modules
      - ./openvswitch:/etc/openvswitch

networks:
  onos_test_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24